# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zvRyKPfCufio7nuwp0zmaKtPzQhhcyFk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**Veri yukleme**"""

veriler = pd.read_csv('/content/Wine.csv')

"""**DATA FRAME (SLICE) DILIMLEME**"""

X = veriler.iloc[:, :-1]
Y = veriler.iloc[:, -1]
# NUMPY ARRAY DIZI DONUSUMU
x = X.values
y = Y.values

from sklearn.model_selection import train_test_split

# verinin yuzde 66 si antrenman icin kullanilsin kalan yuzde 33'u test edilsin diye ayrdik
# random_state rastsal ayirma icin kullaniliyor ayni degeri alan her kod ayni ayrimi yapar
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

"""**Verilerin normalize edilme islemi**"""

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

# burasi bir tur normalizasyon islemi anlatiyor (x-mean)/standar_deviation denklemini kullanir
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

"""**PCA**"""

from sklearn.decomposition import PCA

pca = PCA(n_components = 2)

X_trainApca = pca.fit_transform(X_train)
X_testApca  = pca.transform(X_test)

from sklearn.linear_model import LogisticRegression
# pca'dan once
logReg = LogisticRegression(random_state=0)
logReg.fit(X_train, y_train)
y_pred = logReg.predict(X_test)

# pca'dan sonra
logRegApca = LogisticRegression(random_state=0)
logRegApca.fit(X_trainApca, y_train)
y_predApca = logRegApca.predict(X_testApca)

from sklearn.metrics import confusion_matrix

print('before PCA \n')
cm = confusion_matrix(y_test, y_pred)
print(cm , '\n')

print('after PCA \n')
cmApca = confusion_matrix(y_test, y_predApca)
print(cmApca , '\n')

print('aralarindaki farklar')
cmFark = confusion_matrix(y_pred, y_predApca)
print(cmFark , '\n')

